import 'dart:typed_data';
import 'package:docsera/screens/home/health/pages/visit_reports/visit_report_model.dart';
import 'package:flutter/services.dart' show rootBundle;
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:docsera/app/const.dart';
import 'package:docsera/gen_l10n/app_localizations.dart';

class VisitReportPdfGenerator {
  static Future<Uint8List> generatePdf({
    required VisitReport report,
    required AppLocalizations t,
    required bool isArabic,
  }) async {
    final pdf = pw.Document();
    final mainColor = PdfColor.fromInt(AppColors.main.value);

    // ===== FONTS =====
    final fontRegularData =
    await rootBundle.load('assets/fonts/Cairo-Regular.ttf');
    final fontBoldData =
    await rootBundle.load('assets/fonts/Cairo-Bold.ttf');
    final cairoRegular = pw.Font.ttf(fontRegularData);
    final cairoBold = pw.Font.ttf(fontBoldData);

    final pdfTheme = pw.ThemeData.withFont(
      base: cairoRegular,
      bold: cairoBold,
    );

    // ===== LOGO =====
    pw.SvgImage? logoSvg;
    try {
      final svgString =
      await rootBundle.loadString('assets/images/docsera_main.svg');
      logoSvg = pw.SvgImage(svg: svgString);
    } catch (_) {
      logoSvg = null;
    }

    // ===== TEXTS =====
    final visitInfoTitle = isArabic ? "معلومات الزيارة" : "Visit Information";
    final diagnosisTitle = isArabic ? "التشخيص" : "Diagnosis";
    final recommendationsTitle = isArabic ? "التوصيات" : "Recommendations";
    final extraInfoTitle = isArabic ? "معلومات إضافية" : "Additional Information";

    final doctorLabel = isArabic ? "الطبيب" : "Doctor";
    final clinicLabel = isArabic ? "العيادة" : "Clinic";
    final dateLabel = isArabic ? "تاريخ الزيارة" : "Date";
    final idLabel = isArabic ? "رقم التقرير" : "Report ID";
    final addressLabel = isArabic ? "العنوان" : "Address";
    final signatureLabel = isArabic ? "توقيع الطبيب" : "Doctor Signature";

    String formatDate(DateTime d) {
      final day = d.day.toString().padLeft(2, '0');
      final month = d.month.toString().padLeft(2, '0');
      final year = d.year.toString();
      return isArabic ? "$day/$month/$year" : "$year-$month-$day";
    }

    final visitDate = formatDate(report.date);

    // ===== PAGE THEME =====
    final pageTheme = pw.PageTheme(
      margin: const pw.EdgeInsets.all(32),
      theme: pdfTheme,
      textDirection: isArabic ? pw.TextDirection.rtl : pw.TextDirection.ltr,
    );

    // ===== PAGE =====
    pdf.addPage(
      pw.Page(
        pageTheme: pageTheme,
        build: (context) {
          return pw.Column(
            crossAxisAlignment: isArabic
                ? pw.CrossAxisAlignment.end
                : pw.CrossAxisAlignment.start,
            children: [
              _header(report, mainColor, cairoBold, cairoRegular, visitDate, idLabel, dateLabel, logoSvg, isArabic),

              pw.SizedBox(height: 20),

              _section(
                title: visitInfoTitle,
                color: mainColor,
                cairoBold: cairoBold,
                child: _infoSection(report, doctorLabel, clinicLabel, dateLabel, idLabel, visitDate, cairoRegular, isArabic),
              ),

              if (report.diagnosis != null && report.diagnosis!.isNotEmpty) ...[
                pw.SizedBox(height: 14),
                _section(
                  title: diagnosisTitle,
                  color: mainColor,
                  cairoBold: cairoBold,
                  child: pw.Text(
                    report.diagnosis!,
                    style: pw.TextStyle(font: cairoRegular, fontSize: 11),
                  ),
                ),
              ],

              if (report.recommendation != null && report.recommendation!.isNotEmpty) ...[
                pw.SizedBox(height: 14),
                _section(
                  title: recommendationsTitle,
                  color: mainColor,
                  cairoBold: cairoBold,
                  child: pw.Text(
                    report.recommendation!,
                    style: pw.TextStyle(font: cairoRegular, fontSize: 11),
                  ),
                ),
              ],

              pw.SizedBox(height: 14),

              _section(
                title: extraInfoTitle,
                color: mainColor,
                cairoBold: cairoBold,
                child: _extraInfo(report, addressLabel, signatureLabel, cairoRegular, isArabic),
              ),

              pw.Spacer(),
              pw.Align(
                alignment: isArabic ? pw.Alignment.centerLeft : pw.Alignment.centerRight,
                child: pw.Text(
                  isArabic
                      ? "تم توليد التقرير عبر DocSera © 2025"
                      : "Generated by DocSera © 2025",
                  style: pw.TextStyle(font: cairoRegular, fontSize: 8),
                ),
              ),
            ],
          );
        },
      ),
    );

    return pdf.save();
  }

  // ---------------------------------------------------------------------------
  // --------------------------  INTERNAL BUILDERS  ----------------------------
  // ---------------------------------------------------------------------------

  static pw.Widget _header(
      VisitReport report,
      PdfColor color,
      pw.Font bold,
      pw.Font regular,
      String date,
      String idLabel,
      String dateLabel,
      pw.SvgImage? logoSvg,
      bool isArabic,
      ) {
    return pw.Container(
      padding: const pw.EdgeInsets.all(14),
      decoration: pw.BoxDecoration(
        gradient: pw.LinearGradient(
          colors: [
            PdfColor.fromInt(0xFFE6F5F4),
            PdfColors.white,
          ],
        ),
        borderRadius: pw.BorderRadius.circular(14),
        border: pw.Border.all(color: PdfColor.fromInt(0xFFDDEEEE)),
      ),
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.center,
        children: [
          pw.Row(
            mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
            children: [
              _medicalCross(color),
              pw.SizedBox(height: 13, child: logoSvg ?? pw.Text("DocSera", style: pw.TextStyle(font: bold, fontSize: 16, color: color))),
              // _doctorSilhouette(color),
            ],
          ),
          pw.SizedBox(height: 12),
          pw.Text(
            isArabic ? "تقرير زيارة طبية" : "Medical Visit Report",
            style: pw.TextStyle(font: bold, fontSize: 14, color: PdfColor.fromInt(0xFF006A6E)),
          ),
          pw.SizedBox(height: 6),
          pw.Text(report.doctorName, style: pw.TextStyle(font: regular, fontSize: 11)),
          pw.Text("$dateLabel: $date", style: pw.TextStyle(font: regular, fontSize: 9)),
          pw.Text("$idLabel: ${report.appointmentId}", style: pw.TextStyle(font: regular, fontSize: 9)),
        ],
      ),
    );
  }

  static pw.Widget _medicalCross(PdfColor color) {
    return pw.Container(
      width: 28,
      height: 28,
      decoration: pw.BoxDecoration(
        color: PdfColor.fromInt(0xFFE9F6F5),
        borderRadius: pw.BorderRadius.circular(8),
      ),
      child: pw.Center(
        child: pw.Container(
          width: 15,
          height: 15,
          color: color,
          child: pw.Stack(children: [
            pw.Center(child: pw.Container(width: 3, height: 12, color: PdfColors.white)),
            pw.Center(child: pw.Container(width: 12, height: 3, color: PdfColors.white)),
          ]),
        ),
      ),
    );
  }

  static pw.Widget _doctorSilhouette(PdfColor color) {
    return pw.Container(
      width: 28,
      height: 28,
      decoration: pw.BoxDecoration(
        color: PdfColor.fromInt(0xFFE9F6F5),
        borderRadius: pw.BorderRadius.circular(100),
      ),
      child: pw.Stack(
        alignment: pw.Alignment.center,
        children: [
          pw.Positioned(
            top: 5,
            child: pw.Container(
              width: 10,
              height: 10,
              decoration: pw.BoxDecoration(color: color, borderRadius: pw.BorderRadius.circular(50)),
            ),
          ),
          pw.Positioned(
            bottom: 4,
            child: pw.Container(
              width: 16,
              height: 10,
              decoration: pw.BoxDecoration(color: color, borderRadius: pw.BorderRadius.circular(6)),
            ),
          ),
        ],
      ),
    );
  }

  // ========================== VISIT INFO =============================

  static pw.Widget _infoSection(
      VisitReport report,
      String doctorLabel,
      String clinicLabel,
      String dateLabel,
      String idLabel,
      String visitDate,
      pw.Font font,
      bool isArabic,
      ) {
    return pw.Column(
      crossAxisAlignment:
      isArabic ? pw.CrossAxisAlignment.end : pw.CrossAxisAlignment.start,
      children: [
        _row(doctorLabel, report.doctorName, font, isArabic),
        if (report.clinicName != null)
          pw.SizedBox(height: 5),
        if (report.clinicName != null)
          _row(clinicLabel, report.clinicName!, font, isArabic),

        pw.SizedBox(height: 5),
        _row(dateLabel, visitDate, font, isArabic),
        pw.SizedBox(height: 5),
        _row(idLabel, report.appointmentId, font, isArabic),
      ],
    );
  }

  static pw.Widget _row(
      String label,
      String value,
      pw.Font font,
      bool isArabic,
      ) {
    return pw.Row(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.SizedBox(
          width: 100,
          child: pw.Text(
            label,
            style: pw.TextStyle(
              font: font,
              fontSize: 10,
              color: PdfColors.grey700,
            ),
          ),
        ),
        pw.Expanded(
          child: pw.Text(
            value,
            style: pw.TextStyle(
              font: font,
              fontSize: 10,
              color: PdfColors.black,
            ),
          ),
        ),
      ],
    );
  }


  // ========================== EXTRA INFO =============================

  static pw.Widget _extraInfo(
      VisitReport report,
      String addressLabel,
      String signatureLabel,
      pw.Font font,
      bool isArabic,
      ) {
    return pw.Column(
      crossAxisAlignment:
      isArabic ? pw.CrossAxisAlignment.end : pw.CrossAxisAlignment.start,
      children: [
        if (report.clinicAddress != null)
          _row(addressLabel, report.clinicAddress!, font, isArabic),

        pw.SizedBox(height: 12),
        pw.Text(signatureLabel, style: pw.TextStyle(font: font, fontSize: 10)),
        pw.SizedBox(height: 24),
        pw.Container(width: 130, height: 0.6, color: PdfColors.grey500),
      ],
    );
  }

  /// Section box (title + content)
  static pw.Widget _section({
    required String title,
    required PdfColor color,
    required pw.Font cairoBold,
    required pw.Widget child,
  }) {
    return pw.Container(
      width: double.infinity,
      padding: const pw.EdgeInsets.fromLTRB(12, 10, 12, 12),
      decoration: pw.BoxDecoration(
        borderRadius: pw.BorderRadius.circular(14),
        border: pw.Border.all(
          color: PdfColor.fromInt(0xFFE2ECEB),
          width: 0.7,
        ),
        color: PdfColor.fromInt(0xFFFCFEFE),
      ),
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Text(
            title,
            style: pw.TextStyle(
              font: cairoBold,
              fontSize: 11,
              color: color,
            ),
          ),
          pw.SizedBox(height: 6),
          child,
        ],
      ),
    );
  }


}
